version: "3.9"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root-password
    networks:
      - proxynet
    volumes:
      - ~/volume_db:/data/db:rw
      - ~/volume_configdb:/data/configdb:rw

  otterchat_app:
    image: otterchat_app
#    ports:
#      - "8000:8000"
    environment:
      MONGO_USER: root
      MONGO_PASS: root-password
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
    networks:
      - proxynet
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 2

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - otterchat_app
    ports:
      - "4000:4000"
    networks:
      - proxynet

networks:
  proxynet:
    driver: bridge
    ipam:
      driver: default